System hostname = openbsd
Password for root = *************
Allow root ssh login = no
Change the default console to com0 = yes
Which speed should com0 use = 115200
Setup a user = ansible_admin
Password for user = *************
Full name for user = Ansible Admin
Do you expect to run the X Window System = no
What timezone are you in = Europe/Paris
Network interfaces = vio0
IPv4 address for vio0 = dhcp
Which disk is the root disk = sd0
Use (W)hole disk MBR, whole disk (G)PT, (O)penBSD area or (E)dit = gpt
URL to autopartitioning template for disklabel = http://10.0.2.2/disklabel
Location of sets = http
HTTP Server = 10.0.2.2
Checksum test for site78.tgz failed. Continue anyway? = yes
Unverified sets: site78.tgz. Continue without verification? = yes
